### ISSUE TITLE
how to solve AttributeError: module 'default' has no attribute 'condition_blocks' error?

### ISSUE THREAD

**Issue by MinGiSa** [cool-xuan/vqflow#1]
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
ca-certificates           2024.7.2             haa95532_0
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freia                     0.2                      pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
huggingface-hub           0.21.3                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lightning-utilities       0.11.7                   pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.3                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0
packaging                 24.1                     pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2             py39haa95532_0
platformdirs              4.3.2                    pypi_0    pypi
protobuf                  5.28.1                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.9.0                h6244533_2
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         2.2.0.post0              pypi_0    pypi
pywavelets                1.6.0                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
safetensors               0.4.2                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
sentry-sdk                2.14.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                72.1.0           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
sympy                     1.12                     pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
torch                     2.1.1+cu118              pypi_0    pypi
torchaudio                2.1.1+cu118              pypi_0    pypi
torchinfo                 1.7.2                    pypi_0    pypi
torchmetrics              1.3.1                    pypi_0    pypi
torchvision               0.16.1+cu118             pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2024a                h04d1e81_0
urllib3                   1.26.13                  pypi_0    pypi
vc                        14.40                h2eaa2aa_1
vs2015_runtime            14.40.33807          h98bb1dd_1
wandb                     0.18.0                   pypi_0    pypi
wheel                     0.43.0           py39haa95532_0
yarl                      1.11.1                   pypi_0    pypi
zipp                      3.20.1                   pypi_0    pypi

when i tried to run trainning, below error occurs. can you give me a solution?

`
(vqFlow) C:\Users\user\Desktop\vqflow>python main.py --mode train --dataset visa --class-names all --multi-class --quantize-enable --quantize-type residual --concat-pos --mixed-gaussian --extractor convnextv2_base
Seed set to 9826
-+-+-+-+-+ multi-class +-+-+-+-+-
training on 12 classes: candle, capsules, cashew, chewinggum, fryum, macaroni1, macaroni2, pcb1, pcb2, pcb3, pcb4, pipe_fryum
convnextv2_base picked
Channels of extracted features: [128, 256, 512, 1024]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\vqflow\main.py", line 130, in <module>
    main(c)
  File "C:\Users\user\Desktop\vqflow\main.py", line 120, in main
    train(c)
  File "C:\Users\user\Desktop\vqflow\train.py", line 347, in train
    parallel_flows, fusion_flow = build_vqflow_model(c, output_channels)
  File "C:\Users\user\Desktop\vqflow\models\flow_models.py", line 190, in build_vqflow_model
    n_cond_blocks = c.condition_blocks
AttributeError: module 'default' has no attribute 'condition_blocks'
`

**Comment by TuyubLeticia** [comment]
I'm running into this issue as well, have you solved it?

**Comment by Lee-Gao** [comment]
The same issue!!!

**Comment by MinGiSa** [comment]
> I'm running into this issue as well, have you solved it?

I haven't solved it yet, and I currently have no intention of testing this model anymore.
